name: AndroidLint

on: ["workflow_dispatch"]

jobs:
  android_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - run: ./gradlew lint
      - uses: yutailang0119/action-android-lint@v1.1.0
        with:
          xml_path: build/reports/*.xml