# This action will convert newly committed TODO comments to GitHub issues on push.
# It will also optionally close the issues if the TODOs are removed in a future commit.

# https://github.com/marketplace/actions/todo-to-issue

name: "TODO to Issue"
on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.1"
        id: "todo"